debug:
  verbose: True               # Whether to log information and warnings

arm:
  ip_address: '192.168.1.196' # The IP address of the controlbox for the xArm

gripper:
  approach: left             # [NOTE] Options: left, front